### ISSUE TITLE
chocolat favoris review

### ISSUE THREAD

**Issue by stephaniekuan** [konwen/blog#8]

**Comment by stephaniekuan** [comment]
![img_0092](https://cloud.githubusercontent.com/assets/26073412/23631179/a502e998-028b-11e7-8179-a4f1cfb8f0e9.JPG)
![img_0093](https://cloud.githubusercontent.com/assets/26073412/23631180/a5042f06-028b-11e7-9d6d-4ba00f7fcd38.JPG)
![img_0094](https://cloud.githubusercontent.com/assets/26073412/23631181/a505e652-028b-11e7-83e1-08cf018e7316.JPG)
![img_0095](https://cloud.githubusercontent.com/assets/26073412/23631183/a5089640-028b-11e7-94ef-26acca6efbd7.JPG)
![img_0096](https://cloud.githubusercontent.com/assets/26073412/23631182/a5073228-028b-11e7-801a-3a990b550188.JPG)
![img_0097](https://cloud.githubusercontent.com/assets/26073412/23631184/a50c9286-028b-11e7-87bd-25973d3aef2e.JPG)
![img_0098](https://cloud.githubusercontent.com/assets/26073412/23631185/a50ceec0-028b-11e7-8c2f-6debd66b0fca.JPG)
![img_0099](https://cloud.githubusercontent.com/assets/26073412/23631186/a50dbd64-028b-11e7-9f32-caa3e0f2d34c.JPG)
![img_0100](https://cloud.githubusercontent.com/assets/26073412/23631187/a512410e-028b-11e7-9ef5-baf2c694d7ee.JPG)
![img_0101](https://cloud.githubusercontent.com/assets/26073412/23631188/a513826c-028b-11e7-96de-18dc27c991ae.JPG)
![img_0102](https://cloud.githubusercontent.com/assets/26073412/23631189/a5144f94-028b-11e7-954c-acca04f86b44.JPG)

**Comment by stephaniekuan** [comment]
@konwen please edit

**Comment by konwen** [comment]
@stephaniekuan 2 were unusable

![20170305-a5144f94-028b-11e7-954c-acca04f86b44](https://cloud.githubusercontent.com/assets/18632711/23689350/f77f624e-0387-11e7-8c78-f8916e5cb949.jpg)
![20170305-a512410e-028b-11e7-9ef5-baf2c694d7ee](https://cloud.githubusercontent.com/assets/18632711/23689353/f784a740-0387-11e7-8739-b4ff4426da29.jpg)
![20170305-a513826c-028b-11e7-96de-18dc27c991ae](https://cloud.githubusercontent.com/assets/18632711/23689352/f781354c-0387-11e7-9ec4-f6bd5d727310.jpg)
![20170305-a50dbd64-028b-11e7-9f32-caa3e0f2d34c](https://cloud.githubusercontent.com/assets/18632711/23689355/f7856b62-0387-11e7-9dbe-e02aaab80018.jpg)
![20170305-a50ceec0-028b-11e7-8c2f-6debd66b0fca](https://cloud.githubusercontent.com/assets/18632711/23689354/f784fda8-0387-11e7-8634-d14c9a60d03b.jpg)
![20170305-a5089640-028b-11e7-94ef-26acca6efbd7](https://cloud.githubusercontent.com/assets/18632711/23689351/f7809a9c-0387-11e7-8133-d60e076ae711.jpg)
![20170305-a505e652-028b-11e7-83e1-08cf018e7316](https://cloud.githubusercontent.com/assets/18632711/23689356/f789b136-0387-11e7-8e0a-da31c399b7d0.jpg)
![20170305-a5042f06-028b-11e7-9d6d-4ba00f7fcd38](https://cloud.githubusercontent.com/assets/18632711/23689358/f78e5542-0387-11e7-985a-543d78e52947.jpg)
![20170305-a502e998-028b-11e7-8179-a4f1cfb8f0e9](https://cloud.githubusercontent.com/assets/18632711/23689357/f78d0b1a-0387-11e7-8814-bed608576bdd.jpg)
